version: 0.2

phase:
  pre_build:
    commands:
      - echo Install packages
      - rm -rf package-lock.json
  build:
    commands:
      - echo Create build...
      - npm install
  post_build:
    commands:
      - echo Removing unnecessary files...
      - rm -rf node_modules/
artifacts:
  base-directory: '.'
  files:
    - '**/*'